eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.46:8761/eureka/
      
server:
  port: 8763
  
spring:
  application:
    name: product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.1.40:3306/eshop
    username: root
    password: root
  rabbitmq:
    host: 192.168.1.40
    port: 5672
    username: rabbitadmin
    password: 123456
    
logging:
  level:
     com.kish.eshop.product.mapper : debug